config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about'
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name,  uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50}

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = book.id
    if @book_comment.save
      redirect_to book_path(book)
    else
      @book = Book.new
      @book1 = book
      render 'books/show'
    end
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.new
    @book1 = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])

    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    # flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])

    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<!--<p id="notice"></p>-->
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3 class = 'text-danger'><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <div class = 'text-danger'><%= message %></div>
        <% end %>
      <% end %>
      <%= form_with model: @book, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <div>
        <%= f.submit 'Update Book' , class: 'btn btn-success'%>
        </div>
      <% end %>
      <%= link_to 'Show', book_path(@book.id) ,class: 'book_30857' %>
      |
      <%= link_to 'Back', books_path ,class: 'back' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
<% if @book.errors.any? %>
  <h3 class = 'text-danger'><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
    <div class = 'text-danger'><%= message %></div>
  <% end %>
<% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <!--<img class="attachment user profile_image fallback" src="/assets/no_image-72379a4da21cb04a58337cf92d85bc39f8d534cbc78254c2085acaca82236bfa.jpg"><table class="table">-->
        <%= attachment_image_tag @user, :profile_image , :fill, 63, 63, fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to '',edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog text-black' %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image , :fill, 40, 40, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do%>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), class: 'text-danger',method: :delete do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(book), class: 'text-primary',method: :post do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
              <% end %>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
<% if @book_comment.errors.any? %>
  <h3 class = 'text-danger'><%= @book_comment.errors.count %> error prohibited this obj from being saved:</h3>
  <% @book_comment.errors.full_messages.each do |message| %>
    <div class = 'text-danger'><%= message %></div>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @book1.user, :profile_image , :fill, 63, 63, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @book1.user.name %></th>
          </tr>
          <tr></tr>
            <th>introduction</th>
            <th><%= @book1.user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to '', edit_user_path(@book1.user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
        <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book1.user_id) do %>
                <%= attachment_image_tag @book1.user, :profile_image , :fill, 40, 40, fallback: "no_image.jpg" %>
                <br><%= @book1.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book1.id) do%>
                <%= @book1.title %>
              <% end %>
            </td>
            <td><%= @book1.body %></td>
            <% if @book1.user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book1.id) , class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@book1.id), method: :delete ,class: 'btn btn-sm btn-danger' %></td>
            <% end %>
            <% if @book1.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(@book1), class: 'text-danger',method: :delete do %>
                <i class="fas fa-heart"></i><%= @book1.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(@book1), class: 'text-primary',method: :post do %>
                <i class="fas fa-heart"></i><%= @book1.favorites.count %>
              <% end %>
            </td>
            <% end %>
            <td>
              コメント数：<%= @book1.book_comments.count %>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
      <% @book1.book_comments.each do |book_comment| %>
      <div>
        <%= attachment_image_tag book_comment.user, :profile_image , :fill, 40, 40, fallback: "no_image.jpg" %>
        <%= book_comment.user.name %>
        <%= book_comment.comment %>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: 'btn btn-sm btn-danger',method: :delete %>
        <% end %>
      </div>
      <% end %>
      </div>
      <div>
        <%= form_with(model:[@book1, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Users', users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>

            <% else %>
            <li class="nav-item">
              <%= link_to " Home", "/", class: 'fas fa-home nav-link text-light' %>
            </li>
            <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>

            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    </header>

    <%= yield %>

    <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
      <h3 class = 'text-danger'><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <% @user.errors.full_messages.each do |message| %>
          <div class = 'text-danger'><%= message %></div>
        <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true %>
          <!--<input class="form-control name" type="text" value="ueda" name="user[name]" id="user_name">-->
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image %>
          <!--<input value="{}" data-reference="4ec1d3acb7555e68a6e5917f8acd0763" type="hidden" name="user[profile_image]"><input class="form-control-file user_image" data-reference="4ec1d3acb7555e68a6e5917f8acd0763" include_hidden="false" type="file" name="user[profile_image]" id="user_profile_image">-->
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true %>
          <!--<textarea class="form-control introduction" name="user[introduction]" id="user_introduction"></textarea>-->
        </div>
        <div class="form-group">
          <%= f.submit 'Update User' %>
          <!--<input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">-->
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--<p id="notice"></p>-->
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image , :fill, 63, 63, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        
        <%= link_to '', edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
        <h4>Title</h4>
        <div><%= f.text_field :title %></div>
        <h4>Body</h4>
        <div><%= f.text_area :body %></div>
        <div><%= f.submit 'Create Book' %></div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image , :fill, 40, 40, fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td>
              <%= link_to 'Show', user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image , :fill, 63, 63, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody><tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to "", edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
        <h4>Title</h4>
        <div><%= f.text_field :title %></div>
        <h4>Body</h4>
        <div><%= f.text_area :body %></div>
        <div><%= f.submit 'Create Book' %></div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image , :fill, 40, 40, fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do%>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(book), class: 'text-danger',method: :delete do %>
                <i class="fas fa-heart"></i><%= book.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(book), class: 'text-primary',method: :post do %>
                <i class="fas fa-heart"></i><%= book.favorites.count %>
              <% end %>
            </td>
            <% end %>
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>